---
title: "Figures Panel 1 - Clinical Impact: Mac LA  (TREM2 +)"
author: "Cristiane"
date: "2023-04-03"
output: html_document
---

```{r}
.libPaths("~/Path/")
library(ggplot2)
library(TCGAbiolinks)
library(dplyr)
library(tibble)
library(survival)
library(survminer)
library(readr)
library(readxl)
library(BayesPrism)
library(lubridate)
library(Seurat)
library(Nebulosa)

setwd("~/Path")
```

```{r}
theme_manuscript <- function(base_size=10, base_family="arial") {
  library(grid)
  (ggthemes::theme_foundation(base_size=base_size)
    + theme(plot.title = element_text(hjust = 0.5,size = base_size),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            panel.border = element_rect(colour = NA),
            axis.title.y = element_text(angle=90,vjust =2,size = base_size),
            axis.title.x = element_text(vjust = -0.2,size = base_size),
            axis.text = element_text(size = base_size), 
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_line(colour="#f0f0f0"),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "bottom",
            legend.direction = "horizontal",
            legend.key.size= unit(0.5, "cm"),
            legend.spacing = unit(0, "cm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(size=base_size)
    ))
}

```

```{r}
pal_celltype = c('Malignant Cells' = '#E92663', 
        'Epithelial Cells' = '#F06292',
        'T/NK Cells' = '#0288D1', 
        'B Cells' = '#0097A7', 
        'pDC' = '#00579B', 
        'Myeloid Cells' = '#821764', 
        'Fibroblasts' = '#FFC107',
        'Endothelial Cells' = '#FF7043')

pal_cellStates=c("Mac_Angio" = "#DC4A82",
        "Mac_Hypo" = "#FFA8DE",
        "Mac_IFN"= "#6B6AF4",
        "Mac_LA" = "#BD26DE",
        "Mac_Alv-like"= "#CFB8D9",
        "Mac_Rec" = "#BF8FFF",
        "Mac_AgPres" = "#00AEEE",
        "RTM_IM"= "#1be19f",
        "RTM_IFN" = "#a2db71",
        "RTM_LA"= "#4ddfc8","RTM-like_MT"= "#579C99", 'Mono_CD14_FOS+' = "#ffaf65", 'Mono_CD14_FOS-' = "#ef3142", 'Mono_FCG3RA' = "#755c46", 'Mono_IL1B' = "#d35b00",'MonoInter_CLEC10A' = "#b88b97", 'MonoInter_CXCL10' = "#b0003b",'cDC2A_AREG' = "#45a4d5", 'cDC2_CXCL8' = "#91b0b9", 'cDC2_CD14' = "#2e525e", 'cDC2B_FCER1A' = "#beaac1",
                'cDC1_CLEC9A' = "#477784", 'cDC2_CD207' = "#86638c", 'cDC2_FCGR3A' = "#cfa8d5", 'cDC_LAMP3' = "#a2c6ff", "pDC" = "#00579B", 'Mast_cells' = '#821764',"Neutrophil_CXCL8"= "#6f5fa7", "Neutrophil_MMP9"= "#00a8c7","Neutrophil_TAGLN2"="#a0d8a8")
```


```{r}
#Read datas
load("~/data_fig6.RData")
data_seurat=readRDS("~/data_seurat.rds")
```

```{r fig.height=4, fig.width=5}
## Mean Celltypes
head(df_meanCelltypes)

df_meanCelltypes$variable=ifelse(df_meanCelltypes$variable == "BRCA_Basal", "BRCA_TNBC", df_meanCelltypes$variable)

df_meanCelltypes$celltype = factor(df_meanCelltypes$celltype , levels = c("Endothelial Cells", "Fibroblasts","pDC","B Cells","T/NK Cells","Myeloid Cells","Epithelial Cells","Malignant Cells"))

p_cells=ggplot(data=df_meanCelltypes, aes(x=variable, y=value, fill=celltype)) + geom_bar(stat="identity") + theme_classic() + coord_flip() +labs(title="Deconvolution Analysis in TCGA cohort", x="Tumor Type", y = "Mean Expression of subpopulations cells") + theme_manuscript() + scale_fill_manual(values=pal_celltype) +guides(fill=guide_legend(title="Cell Types", ncol = 2, direction = "horizontal"))+ theme(axis.text.y = element_text(hjust = 1, size = 10), axis.title.x = element_text(size = 9), axis.text.x = element_text(hjust = 1, size = 8),legend.position = "bottom")
p_cells
# dev.off()
```

```{r}
head(df_meanCellstates)

df_meanCellstates$variable=ifelse(df_meanCellstates$variable == "BRCA_Basal", "BRCA_TNBC", df_meanCellstates$variable)

df_meanCellstates$celltype = factor(df_meanCellstates$celltype, levels = c("B_cells", "cDC_LAMP3","cDC1_CLEC9A","cDC2_CD14"        ,"cDC2_CD207","cDC2_CXCL8","cDC2_FCGR3A","cDC2A_AREG","cDC2B_FCER1A","pDC","Mac_Alv-like","Mac_Angio","Mac_Hypo","Mac_IFN","Mac_LA","Mac_Rec","Mac_AgPres","RTM_IFN", "RTM_IM","RTM_LA","RTM-like_MT","Mast_cells","Mono_CD14_FOS-","Mono_CD14_FOS+","Mono_FCG3RA","Mono_IL1B","MonoInter_CXCL10" ,"MonoInter_CLEC10A","Neutrophil_CXCL8" , "Neutrophil_MMP9","Neutrophil_TAGLN2","NK_cyto","NK_rest","NKT", "TCD4_em","TCD4_ex","TCD4_naive","TCD4_reg" ,"TCD8_em","TCD8_ex","TCD8_naive","TGD","Endothelial","Fibroblasts","Epithelial Cells","Malignant Cells"))
```


```{r fig.height=5, fig.width=10}
## Mean cell states

patterns = c("Mac", "RTM", "pDC", "cDC", "Mono", "Mac_Alv-like")
p_celltypes=ggplot(data=df_meanCellstates[grepl(paste(patterns, collapse="|"), df_meanCellstates$celltype),], aes(x=variable, y=value, fill=celltype)) +
    geom_bar(stat="identity", width=0.8) + theme_classic() + coord_flip() + scale_fill_manual(values = pal_cellStates) + theme_manuscript(base_size = 10)+ guides(fill=guide_legend(title="Cell States",ncol = 4, title.position = "top")) +
  facet_wrap(celltype2 ~ ., scales = "free") + theme(legend.position="bottom", legend.text = element_text(size=10)) + theme(panel.grid.major.x = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) + labs(y="Mean Expression of subpopulations myeloid cells") + theme(axis.text.y = element_text(hjust = 1, size = 10), axis.title.x = element_text(size = 10))+labs(title="BayesPrism - Deconvolution Analysis in TCGA cohort", 
         x="Tumor Type", y = "Mean Expression of subpopulations myeloid cells")

p_celltypes

```

```{r fig.height=3, fig.width=6}
macro_pal = c(
  "Mac_Alv-like" = "#8B87FE",
  "Mac_Angio" = "#DC4A82",
  "Mac_Hypo" = "#FFA8DE",
  "Mac_IFN" = "#6B6AF4",
  "Mac_LA" = "#BD26DE",
  "Mac_Prolif" = "#CFB8D9",
  "Mac_Rec" = "#BF8FFF",
  "Mac_AgPres" = "#00AEEE",
  "RTM_IM" = "#1be19f",
  "RTM_IFN" = "#a2db71",
  "RTM_LA" = "#4ddfc8",
  "RTM-like_MT" = "#579C99"
)


data_seurat$celltype=ifelse(data_seurat$celltype == "Mac_Reg", "Mac_AgPres",data_seurat$celltype )

Idents(data_seurat) = data_seurat$celltype

vln_trem2=VlnPlot(data_seurat, c("TREM2"), split.by = 'celltype', sort = 'incresing', cols = macro_pal, pt.size=0) + NoLegend()
vln_trem2
```


```{r fig.height=2, fig.width=8}
umap_trem2_pd1=plot_density(data_seurat, features = c('TREM2', 'PDCD1'), joint = T, pal = 'magma', reduction = "UMAP") & NoAxes()
umap_trem2_pd1
```



###### Mac_LA  (TREM2 +)  BRCA: TNBC ###

```{r}
head(TCGA_BRCA)["Mac_LA"]
head(TMAfinal_BRCA)[1:3]
```
```{r}
#### Basal ####
Basal=TCGA_BRCA[TCGA_BRCA$BRCA_Subtype_PAM50 == "Basal",]

# 1. Determine the optimal cutpoint of variables
res.cut <- surv_cutpoint(Basal, time = "OS.time5", event = "OS.status5",
                         variables ="Mac_LA")

summary(res.cut)
#plot(res.cut, features, palette = "npg", bins = 30, xscale = "log2") 

res.cat <- surv_categorize(res.cut)
head(res.cat)

Basal$Mac_LA_group = res.cat$Mac_LA
```
```{r}
##OS
stats <- summary(coxph(Surv(OS.time5, OS.status5) ~ Mac_LA_group, data = Basal))
fit <- survfit(Surv(OS.time5, OS.status5) ~ Mac_LA_group, data = Basal)
surv_Basal_MacLA =ggsurvplot(fit, ylab = "Overall Survival Probability",xlab = "Time in years",palette = c("#DB7093","#20b2aa"),
                             surv.median.line = c("hv"), cumcensor = F,  conf.int = F ,risk.table = F, pval = F,
                             risk.table.y.text.col = T, # colour risk table text annotations.
                             risk.table.y.text = FALSE, font.main = c(9), font.legend = c(8), font.y = c(10),font.x = c(10), font.caption = c(10),
                             font.tickslab = c(10),legend.labs=c("Mac_LA High","Mac_LA Low"), fontsize = 3,risk.table.height = 0.3, pval.size = 3.5, censor.size = 2,
                             font.ytickslab = c(10))

surv_Basal_MacLA$plot = surv_Basal_MacLA$plot + theme(plot.title = element_text(hjust = -0.1,size = 9))
surv_Basal_MacLA$table =  surv_Basal_MacLA$table + theme(axis.title.y = element_text(vjust =2,size = 10),
                                                         axis.title.x = element_text(vjust = -0.2,size = 10),
                                                         plot.title = element_text(hjust = 0,size = 10), axis.text.x = element_text(size = 10))

surv_Basal_MacLA$plot <-surv_Basal_MacLA$plot + ggplot2::annotate(
  "text",
  x = 0.20, y = 0,
  vjust = 0, hjust = 0,
  label = paste("p = ",signif(stats$sctest["pvalue"], 2) ,"\nHR = ",signif(stats$coef[2],2), "\nCI.95 = ", signif(stats$conf.int[, "lower .95"],2), " ~ ", signif(stats$conf.int[,"upper .95"],2),sep = ""), size = 3)


## PFI
stats <- summary(coxph(Surv(PFI.time5, PFI.status5) ~ Mac_LA_group, data = Basal))
fit <- survfit(Surv(PFI.time5, PFI.status5) ~ Mac_LA_group, data = Basal)
surv_Basal_MacLA_pfi =ggsurvplot(fit, xlab = "Time in years",ylab = "Progression-Free Survival Probability",palette = c( "#DB7093","#20b2aa"), surv.median.line = c("hv"), cumcensor = F,  conf.int = F ,risk.table = F, pval = F,risk.table.y.text.col = T,  risk.table.y.text = FALSE, font.main = c(9), font.legend = c(8), font.y = c(10),font.x = c(10), font.caption = c(10), 
                             font.tickslab = c(10),legend.labs=c("Mac_LA High","Mac_LA Low"), fontsize = 3,risk.table.height = 0.3, pval.size = 3.5, censor.size = 2,font.ytickslab = c(10))

surv_Basal_MacLA_pfi$plot = surv_Basal_MacLA_pfi$plot + theme(plot.title = element_text(hjust = -0.1,size = 9))
surv_Basal_MacLA_pfi$table =  surv_Basal_MacLA_pfi$table + theme(axis.title.y = element_text(vjust =2,size = 10),
                                                         axis.title.x = element_text(vjust = -0.2,size = 10),
                                                         plot.title = element_text(hjust = 0,size = 10), axis.text.x = element_text(size = 10))


surv_Basal_MacLA_pfi$plot <-surv_Basal_MacLA_pfi$plot +ggplot2::annotate(
  "text",
  x = 0.20, y = 0,
  vjust = 0, hjust = 0,
  label = paste("p = ",signif(stats$sctest["pvalue"], 2) ,"\nHR = ",signif(stats$coef[2],2), "\nCI.95 = ", signif(stats$conf.int[, "lower .95"],2), " ~ ", signif(stats$conf.int[,"upper .95"],2),sep = ""), size = 3)


```

### IHC

```{r}
TMAfinal_BRCA$OS_time_interval_years = TMAfinal_BRCA$OS_time_interval/365.25

TMAfinal_BRCA$OS_time5= ifelse(TMAfinal_BRCA$OS_time_interval_years >= 5 , 5, TMAfinal_BRCA$OS_time_interval_years)
TMAfinal_BRCA$OS_status5= ifelse(TMAfinal_BRCA$OS_time_interval_years>= 5, 0, TMAfinal_BRCA$yn_obito)

TMAfinal_BRCA$EFS_time_interval_years <- TMAfinal_BRCA$EFS_time_interval/365.25
## 5 years
TMAfinal_BRCA$EFS_time5yrs= ifelse(TMAfinal_BRCA$EFS_time_interval_years >= 5, 5, TMAfinal_BRCA$EFS_time_interval_years)
TMAfinal_BRCA$EFS_status5yrs= ifelse(TMAfinal_BRCA$EFS_time_interval_years >= 5, 0, TMAfinal_BRCA$EFS_status)
```


```{r}
# separar em dias
res.cut <- surv_cutpoint(TMAfinal_BRCA, time = "OS_time5", event = "OS_status5",
                         variables = "Value_TREM2")

summary(res.cut)
plot(res.cut,"Value_TREM2", palette = "npg", bins = 30, xscale = "log2") 

res.cat <- surv_categorize(res.cut)
head(res.cat)

TMAfinal_BRCA$TREM2_group = res.cat$Value_TREM2
table(TMAfinal_BRCA$TREM2_group)
```

```{r}
#plotar em anos
stats= summary(coxph(Surv(OS_time5, OS_status5) ~ TREM2_group, data = TMAfinal_BRCA))
fit <- survfit(Surv(OS_time5, OS_status5) ~ TREM2_group, data = TMAfinal_BRCA)
OS_TREM_BRCA =ggsurvplot(fit, xlab = "Time in years",surv.median.line = c("hv"), cumcensor = F,  conf.int = F ,risk.table = F, pval = F,ylab = "Overall Survival Probability",
                risk.table.y.text.col = T, # colour risk table text annotations.
                 risk.table.y.text = FALSE, font.main = c(9), font.legend = c(8), font.y = c(10),font.x = c(10), font.caption = c(10), 
                 font.tickslab = c(10), fontsize = 3,risk.table.height = 0.3, pval.size = 3.5, censor.size = 2,
                 font.ytickslab = c(10), legend.labs=c("TREM2 High","TREM2 Low"),
                 palette = c("#db7080","#207cb2"))# break.x.by = 10

OS_TREM_BRCA$plot <-OS_TREM_BRCA$plot + ggplot2::annotate(
  "text",
  x = 0.20, y = 0,
  vjust = 0, hjust = 0,
  label = paste("p = ",signif(stats$sctest["pvalue"], 2) ,"\nHR = ",signif(stats$coef[2],2), "\nCI.95 = ", signif(stats$conf.int[, "lower .95"],2), " ~ ", signif(stats$conf.int[,"upper .95"],2),sep = ""), size = 3)


stats= summary(coxph(Surv(EFS_time5yrs, EFS_status5yrs) ~ TREM2_group, data = TMAfinal_BRCA))
fit <- survfit(Surv(EFS_time5yrs, EFS_status5yrs) ~ TREM2_group, data = TMAfinal_BRCA)
EFS_TREM_BRCA =ggsurvplot(fit, xlab = "Time in years", ylab = "Recurrence-Free Survival Probability",
                 surv.median.line = c("hv"), cumcensor = F,  conf.int = F ,risk.table = F, pval = F,
                 risk.table.y.text.col = T, # colour risk table text annotations.
                 risk.table.y.text = FALSE, font.main = c(9), font.legend = c(8), font.y = c(10),font.x = c(10), font.caption = c(10), legend.labs=c("TREM2 High","TREM2 Low"),
                 font.tickslab = c(10), fontsize = 3,risk.table.height = 0.3, pval.size = 3.5, censor.size = 2,
                 font.ytickslab = c(10),
                 palette = c("#db7080","#207cb2")) 

EFS_TREM_BRCA$plot <-EFS_TREM_BRCA$plot + ggplot2::annotate(
  "text",
  x = 0.20, y = 0,
  vjust = 0, hjust = 0,
  label = paste("p = ",signif(stats$sctest["pvalue"], 2) ,"\nHR = ",signif(stats$coef[2],2), "\nCI.95 = ", signif(stats$conf.int[, "lower .95"],2), " ~ ", signif(stats$conf.int[,"upper .95"],2),sep = ""), size = 3)

```


#### Assoc. Frequency

```{r}
table(TMAfinal_BRCA$CD8)
TMAfinal_BRCA$CD8[which(TMAfinal_BRCA$CD8 %in% 999)] <- NA
TMAfinal_BRCA$CD8[which(TMAfinal_BRCA$CD8 %in% c("0", "1"))] <- "0-1"
TMAfinal_BRCA$CD8[which(TMAfinal_BRCA$CD8 %in% c("10","20","30","40","5"))] <- ">=5"

TMAfinal_BRCA$CD8 <- factor(TMAfinal_BRCA$CD8, levels = c(">=5","0-1"),
                       labels = c("High CD8", "Low CD8"))

table(TMAfinal_BRCA$PD1)
TMAfinal_BRCA$PD1[which(TMAfinal_BRCA$PD1 %in% 999)] <- NA

TMAfinal_BRCA$PD1 <- factor(TMAfinal_BRCA$PD1, levels = c("1","0"),
                       labels = c("High PD1", "Low PD1"))

table(TMAfinal_BRCA$PDL1_CPS)
TMAfinal_BRCA$PDL1_CPS <- factor(TMAfinal_BRCA$PDL1_CPS, levels = c("1","0"),
                            labels = c("High PDL1","Low PDL1"))
names(TMAfinal_BRCA)[29] = "PDL1"
```

```{r}
TMAfinal_BRCA$TREM2_group = ifelse(TMAfinal_BRCA$TREM2_group == "high", "High TREM2", "Low TREM2")

```


```{r}
#TMAfinal_BRCA$TREM2_group = ifelse(TMAfinal_BRCA$TREM2_group == "high", "High TREM2", "Low TREM2")
dat <- table(TMAfinal_BRCA$TREM2_group, TMAfinal_BRCA$CD8)
stats=fisher.test(dat)
TREM2_P1 <- ggplot(TMAfinal_BRCA[!is.na(TMAfinal_BRCA$TREM2_group) & !is.na(TMAfinal_BRCA$CD8) ,],
                                aes(x = TREM2_group, fill = CD8)) + ylab("count")+ xlab("")+
  geom_bar(position="fill") + theme_manuscript()+theme(legend.position = "top", legend.text = element_text(size = 10),axis.text.x = element_text(angle = 0))+
  scale_fill_manual(values=c('#8225BE','#2596BE', '#D4C443'))+guides(fill=guide_legend(ncol = 2, title.position = "top", title = "")) +ggplot2::annotate(
  "text",
  x =1, y = 1.3,
  label = paste("P. Fisher = ",label= round(stats$p.value, digits = 3)), size=4) + ggtitle("TREM2+")


dat <- table(TMAfinal_BRCA$TREM2_group, TMAfinal_BRCA$PD1)
stats=fisher.test(dat)
TREM2_P2 <- ggplot(TMAfinal_BRCA[!is.na(TMAfinal_BRCA$TREM2_group) & !is.na(TMAfinal_BRCA$PD1) ,],
                   aes(x = TREM2_group, fill = PD1)) + theme_manuscript()+
  geom_bar(position="fill") +theme(legend.position = "top", legend.text = element_text(size = 10),axis.text.x = element_text(angle = 0))+xlab("")+ylab("count")+
  scale_fill_manual(values=c('#8225BE','#2596BE', '#D4C443'))+guides(fill=guide_legend(ncol = 2,title.position = "top", title = ""))+ggplot2::annotate(
  "text",
  x =1, y = 1.3,
  label = paste("P. Fisher = ",label= round(stats$p.value, digits = 3)), size=4)+ ggtitle("TREM2+")

dat <- table(TMAfinal_BRCA$TREM2_group, TMAfinal_BRCA$PDL1)
stats=fisher.test(dat)
TREM2_P3 <- ggplot(TMAfinal_BRCA[!is.na(TMAfinal_BRCA$TREM2_group) & !is.na(TMAfinal_BRCA$PDL1) ,],
                   aes(x = TREM2_group, fill =PDL1)) + xlab("")+ ylab("count") +
  geom_bar(position="fill") +theme_manuscript()+theme(legend.position = "bottom", legend.text = element_text(size = 10),axis.text.x = element_text(angle = 0))+
  scale_fill_manual(values=c('#8225BE','#2596BE', '#D4C443'))+guides(fill=guide_legend(ncol = 2,title.position = "top"))+ggplot2::annotate(
  "text",
  x =1, y = 1.3,
  label = paste("P. Fisher = ",label= round(stats$p.value, digits = 3)), size=4)+ ggtitle("TREM2+")
```

```{r fig.height=3, fig.width=7.6}
Plots_TREM2 = cowplot::plot_grid(TREM2_P1, TREM2_P2, nrow = 1)
Plots_TREM2
```

```{r fig.height=4, fig.width=10}
p1=cowplot::plot_grid(p_cells,p_celltypes, nrow = 1, rel_widths = c(1,2),align = "hv", labels = c("A", "B"), label_size = 20)
p1
```

```{r fig.height=3, fig.width=12}
p2=cowplot::plot_grid(vln_trem2,umap_trem2_pd1, nrow = 1, labels = c("C", "D"), label_size = 20, align = "h", hjust = c(-0.5,1,-0.5))
p2
```

```{r fig.height=8, fig.width=12}

p2.1=cowplot::plot_grid(p1,p2, nrow=2, align = "h", rel_widths  = c(1,0.5), rel_heights = c(2,1))
p2.1

```

```{r fig.height=6, fig.width=6}
surv_Basal_MacLA$plot + labs(tag = 'E') + theme(plot.tag = element_text(face = "bold", size=16))+surv_Basal_MacLA_pfi$plot+OS_TREM_BRCA$plot + labs(tag = 'F') + theme(plot.tag = element_text(face = "bold", size=16))+ EFS_TREM_BRCA$plot 
```

```{r}
svg("~/biomarcprogml_ov/results/Script_panel1_clinical/figures_final/fig6a_d.svg", width = 13, height = 9)
p2.1 + theme(panel.background = (element_rect(fill = 'white', colour = 'white'))) 
dev.off()
```




####Supp
```{r}
load("~/data_fig6.RData")
```


```{r}
head(df_meanCellstates)

df_meanCellstates$celltype = factor(df_meanCellstates$celltype, levels = c("B_cells", "cDC_LAMP3","cDC1_CLEC9A","cDC2_CD14"        ,"cDC2_CD207","cDC2_CXCL8","cDC2_FCGR3A","cDC2A_AREG","cDC2B_FCER1A","pDC","Mac_Alv-like","Mac_Angio","Mac_Hypo","Mac_IFN","Mac_LA"    ,"Mac_Rec","Mac_Reg","RTM_IFN", "RTM_IM","RTM_LA","RTM-like_MT","Mast_cells","Mono_CD14_FOS-","Mono_CD14_FOS+","Mono_FCG3RA","Mono_IL1B","MonoInter_CXCL10" ,"MonoInter_CLEC10A","Neutrophil_CXCL8" , "Neutrophil_MMP9","Neutrophil_TAGLN2","NK_cyto","NK_rest","NKT", "TCD4_em","TCD4_ex","TCD4_naive","TCD4_reg" ,"TCD8_em","TCD8_ex","TCD8_naive","TGD","Endothelial","Fibroblasts","Epithelial Cells","Malignant Cells"))
```


```{r fig.height=5, fig.width=10}
## Mean cell states

patterns = c("Neut", "Mast")

p_celltypes=ggplot(data=df_meanCellstates[grepl(paste(patterns, collapse="|"), df_meanCellstates$celltype),], aes(x=variable, y=value, fill=celltype)) +
    geom_bar(stat="identity", width=0.8) + theme_classic() + coord_flip() + scale_fill_manual(values = pal_cellStates) + theme_manuscript(base_size = 10)+ guides(fill=guide_legend(title="Cell States",ncol = 4, title.position = "top")) +
  facet_wrap(celltype2 ~ ., scales = "free") + theme(legend.position="bottom", legend.text = element_text(size=10)) + theme(panel.grid.major.x = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1, size = 10)) + labs(y="Mean Expression of subpopulations myeloid cells") + theme(axis.text.y = element_text(hjust = 1, size = 10), axis.title.x = element_text(size = 10))+labs(title="BayesPrism - Deconvolution Analysis in TCGA cohort", 
         x="Tumor Type", y = "Mean Expression of subpopulations myeloid cells")

p_celltypes + labs(tags="A")+theme(text = element_text(size=16))

```